### ISSUE TITLE
Create the User API

### ISSUE THREAD

**Issue by ErwanLT** [ErwanLT/HumanCloningFacilities#100]
User API

manage user API (CRUD)

we want :
- a UserController
- a UserService
- a UserRepository

**Comment by yekxp** [comment]
Hello, my name is Jakub and I am a student of Technical University in Kosice and software developer in Siemens Healthineers and I would be very happy if I could work on this issue. It would be the part of the course where we have to help a project on GitHub. Could you assign me to it, please?

**Comment by ErwanLT** [comment]
> Hello, my name is Jakub and I am a student of Technical University in Kosice and software developer in Siemens Healthineers and I would be very happy if I could work on this issue. It would be the part of the course where we have to help a project on GitHub. Could you assign me to it, please?

Hello @yekxp thisissue was moved to another project https://github.com/ErwanLT/HackOktoberfest/issues/2
If you still want it, it's all yours, just let me init the project and complete the readme with the data model and it will ready for you.
